Document: setnet
Title: Debian setnet Manual
Author: <insert document author here>
Abstract: This manual describes what setnet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/setnet/setnet.sgml.gz

Format: postscript
Files: /usr/share/doc/setnet/setnet.ps.gz

Format: text
Files: /usr/share/doc/setnet/setnet.text.gz

Format: HTML
Index: /usr/share/doc/setnet/html/index.html
Files: /usr/share/doc/setnet/html/*.html
